export const ENV_KEYS = {
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN,
  STRIPE_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  CLERK_WEBHOOK_SECRET: process.env.SIGNING_SECRET,
}
