import type { Metadata } from 'next'
import { Julius_Sans_One, Poppins } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'

import { StripeProvider } from '@/shared/lib/stripe-context'
import { SelectedProvider } from '@/shared/lib/trascription-context'
import { UnsavedChangesProvider } from '@/shared/lib/unsaved-changes-context'
import { SidebarProvider, SidebarTrigger } from '@/shared/ui/common/sidebar'
import { Sidebar } from '@/widgets/Sidebar'

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['300', '400'],
  subsets: ['latin'],
  display: 'swap',
})

const juliusSans = Julius_Sans_One({
  variable: '--font-julius',
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
  params: Promise<any>
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${poppins.className} ${juliusSans.variable} antialiased`}
        >
          <StripeProvider>
            <UnsavedChangesProvider>
              <SelectedProvider>
                <SidebarProvider defaultOpen={false}>
                  {children}
                </SidebarProvider>
              </SelectedProvider>
            </UnsavedChangesProvider>
          </StripeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
