import type { Metadata } from 'next'
import { Julius_Sans_One, Poppins } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'

import { StripeProvider } from '@/shared/lib/stripe-context'
import { SelectedProvider } from '@/shared/lib/trascription-context'
import { SidebarProvider, SidebarTrigger } from '@/shared/ui/common/sidebar'
import { Header } from '@/widgets/Header'
import { Sidebar } from '@/widgets/Sidebar'

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['300', '400'],
  subsets: ['latin'],
  display: 'swap',
})

const juliusSans = Julius_Sans_One({
  variable: '--font-julius',
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${poppins.className} ${juliusSans.variable} antialiased`}
        >
          <StripeProvider>
            <SelectedProvider>
              <SidebarProvider defaultOpen={false}>
                <Sidebar />
                <SidebarTrigger
                  className='absolute top-0 text-white'
                  size='lg'
                />
                {children}
              </SidebarProvider>
            </SelectedProvider>
          </StripeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
